name: Build and test

on:
  pull_request:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          # cache: "pip" # caching pip dependencies
      - name: Install test requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test.txt
      - name: Run tests
        run: |
          echo "Make sure the review app of this branch is deployed and configured in the test-pep8speaks app"
          pytest
